name: Docker_CI

on:
  push:
    branches: [ "main" ]

jobs:

  test-dumasenko:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the test Docker image
      run: | 
        cd  delievery_service
        docker build . --file Dockerfile.test -t delievery-service
    - name: Run the test Docker image
      run: |
        docker run delievery-service
  
  load-image:

    needs: test-dumasenko

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USENAME_DOCKERHUB }}
          password: ${{ secrets.TOKEN_DOCKERHUB }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./delievery_service
          push: true
          tags: dumasenko/microservices:latest
